---
title: "CA Dashboard in R programming"
author: "Aramis VIllasmil 10509173"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
---

```{r setup, include=FALSE}
library(ggplot2)
library(plotly)
library(plyr)
library(flexdashboard)
library(tidyr)
#
# create some data
setwd("C:\\Users\\Pauli\\Desktop\\tools\\CA\\CAtoolsDashboard")
data<-read.csv('Production_Crops_E_Europe_NOFLAG.csv')

#REMOVE SPREAD COLUMNS "ELEMENT"-----------------------------------------------
a<-new.env()
years<-c("Y1961","Y1962","Y1963","Y1964","Y1965","Y1966","Y1967","Y1968","Y1969","Y1970","Y1971","Y1972","Y1973","Y1974","Y1975","Y1976","Y1977","Y1978","Y1979","Y1980","Y1981","Y1982","Y1983","Y1984","Y1985","Y1986","Y1987","Y1988","Y1989","Y1990","Y1991","Y1992","Y1993","Y1994","Y1995","Y1996","Y1997","Y1998","Y1999","Y2000","Y2001","Y2002","Y2003","Y2004","Y2005","Y2006","Y2007","Y2008","Y2009","Y2010","Y2011","Y2012","Y2013","Y2014","Y2015","Y2016","Y2017")

for (year in years){
  temp<-data[,c("Area","Item","Element",year)];
  a[[year]]<-spread(temp,Element,year);
}#SPREAD() function is in tidyr
  
newdata<-a[["Y1961"]][,c("Area","Item")]

for (year in years){
  newdata<-cbind(newdata,a[[year]][,c("Area harvested","Production","Yield")])
}
names<-colnames(newdata)
newnames<-names<-c(names[1],names[2])

for (year in years){
  newnames<-append(newnames,c(paste("area",year),paste("production",year),paste("yield",year)));
}
colnames(newdata)<-newnames

options(scipen = 999)#get rid of scientific notation
newdat <- na.omit(newdata)
Barley <-newdat[newdat$Item=="Barley",]

Orange <-newdat[newdat$Item=="Oranges",]

maize<- newdat[newdat$Item=="Maize",]

potato<- newdat[newdat$Item=="Potatoes",]               

germany<- newdat[newdat$Area=="Germany",]

ireland<- newdat[newdat$Area=="Ireland",]
View(newdat)
```

PAGE 1
=======================================================================

Row
-----------------------------------------------------------------------

### POTATOES CROP AREA-PRODUCTION 1961
 (1)

```{r}
pp <- ggplot(potato, aes(x=potato$`area Y1961`, y=potato$`production Y1961`)) +
  geom_point(aes(size=potato$`production Y1961`, colour=Area))      # Use hollow circles
ggplotly(pp)
```


### POTATOES CROP AREA-PRODUCTION 2017 (2)

```{r}
qq<- ggplot(potato, aes(x=potato$`area Y2017`, y=potato$`production Y2017`)) +
  geom_point(aes(size=potato$`production Y2017`, colour=potato$Area))
ggplotly(qq)
```

Row
-----------------------------------------------------------------------

### IRELAND AGRICULTURAL OUTPUT (3)

```{r}
ii<- ggplot(ireland, aes(x=ireland$`area Y2017`, y=ireland$`production Y2017`)) +
  geom_point(aes(size=ireland$`production Y2017`, colour=ireland$Item))
ggplotly(ii)
```

### ORANGES (4)

```{r}
oo<- ggplot(Orange, aes(x=Orange$`area Y2017`, y=Orange$`production Y2017`)) +
  geom_point(aes(size=Orange$`production Y2017`, colour=Area))
ggplotly(oo)
```

PAGE 2
=======================================================================

Row
-----------------------------------------------------------------------

### GERMANY AGRICULTURAL OUTPUT 1961 (5)

```{r}
s<- ggplot(germany, aes(x=germany$`area Y1961`, y=germany$`production Y1961`)) + 
  geom_point(aes(size=germany$`production Y1961`, colour=Item))
ggplotly(s)
```

### GERMANY AGRICULTURAL OUTPUT 2017 (6)

```{r}
ss<- ggplot(germany, aes(x=`area Y2017`, y=`production Y2017`)) +
  geom_point(aes(size=`production Y2017`, colour=Item))
ggplotly(ss)
```